name: Contexts
run-name: Contextos de Github 
on:
  push:
    branches: [main]

jobs:
  Explore-Contexts:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Run context ENV
        env: 
          ENV: ${{ toJson(github.env) }}
        run: echo $ENV
      - name: Run context runner 
        env: 
          RUNNER: ${{ toJson(runner) }}
        run: echo $RUNNER
      - name: Run context SHA 
        env: 
          SHA: ${{ toJson(github.sha) }}
        run: echo $SHA

  Explore-Concurrency-First: 
    concurrency:
      group: ${{github.workflow}}-${{github.ref}}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
     - name: Run Concurrency First
       run: echo First Concurrency Job

  Explore-Concurrency-Second:
    concurrency:
      group: ${{github.workflow}}-${{github.ref}}
      cancel-in-progress: true 
    runs-on: ubuntu-latest
    steps:
     - name: Run Concurrency Second
       run: echo Second Concurrency Job

  